### ISSUE TITLE
Move the summary object from the repo_analysis JSON to the outer level

### ISSUE THREAD

**Issue by tonyc856** [bcdasilv/code-style-mining#21]
Instead of summary object being in the repo_analysis, it should be at the same level as the repo_analysis object in the main JSON.

**Comment by bcdasilv** [comment]
Also, rename the fields to be more communicative after this proposed refactoring. For example, 'summary' could be 'analysis_summary' and the 'repo_analysis' field could be 'analyzed_files'.

**Comment by kramsey458** [comment]
There seems to be an issue with the MongoDB on cloud: "pymongo.errors.OperationFailure: cannot create a new collection -- already using 500 collections of 500" is thrown - regardless of collection name or the actual size of the collection. This happened when I was changing code in an attempt to move this JSON object to the upper level. Unsure if this is an error in the code or on the MongoDB host's end.

**Comment by bcdasilv** [comment]
@kramsey458 , are you using one collection per repo? If yes, this is the problem. We should use one collection and add several repos in it.

**Comment by kramsey458** [comment]
@bcdasilv The issue occurred for a single collection with many documents. I fixed the issue by deleting the java-analysis-v01 database (that I created earlier) and the corresponding collections. After removing that database, the error stopped.

**Comment by bcdasilv** [comment]
All right. Thanks. So, although you were not doing 1 collection per repo/json, the issue was indeed what I described because in earlier versions we were doing that. So previous databases stored there were created with that configuration. So globally, we were having nearly 500 collections. If we clean that up by deleting older databases this should not be a problem anymore.
